export type BookingFlowState =
  | "IDLE"
  | "SELECTING_SERVICE"
  | "CONFIRMING_LOCATION"
  | "ADD_DETAILS"
  | "SELECTING_VEHICLE"
  | "SELECTING_PROVIDER"
  | "AWAITING_CONFIRMATION"
  | "TRACKING";